language: r

os:
  - linux
  - osx
  
sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

apt_packages:
  - libgsl-dev
      
brew_packages:
  - gsl

r_packages:
  - covr
  - devtools

r_github_packages:
  - codecov/example-r
  - andrebleier/Xy
  
after_success:
  - Rscript -e 'library(covr);codecov()'